spring:
  application:
    name: spring-AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
#          max-tokens: 100 #max number of tokens in the response
#          temperature: 0.7 #control creativity -> 0: focused - 1: random
    ollama:
      chat:
        options:
          model: llama3.2:1b
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-h2db.sql
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./data/spring-AI-database;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: khanh
    password: 12345
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %magenta(${PID:- }) --- %red([%15.15thread]) %yellow(%-40.40logger{39}): %msg%n%wEx"
  level:
    org.tommap.springai: debug
    org.springframework.ai.chat.client.advisor: debug
